language: java
jdk: oraclejdk8
 
env:
  global:
  - secure: "....encrypted sonar token here....."
 
addons:
  sonarcloud:
    organization: "orga-name-github"
    token:
      secure: $SONAR_TOKEN
 
 before_script:
    #https://docs.travis-ci.com/user/environment-variables/
    # Always run script
    #- $TRAVIS_BUILD_DIR/ci/travis_release_audit.sh
    # CD Sub Projet
    #- cd  $TRAVIS_BUILD_DIR/subproject

script:
- ./mvnw clean install -B
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  # no test  / -DskipTests   or -Dmaven.test.skip=true